version: '2'
services:
  redis:
    restart: always
    image: redis:3.2
    expose:
      - "6379"
  app:
    environment:
        REDIS_URL: redis://redis
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - redis:redis
    ports:
      - "9904:8000"